### ISSUE TITLE
data is not iterable 

### ISSUE THREAD

**Issue by pi0** [unjs/uqr#2]
When passing a nonstring type to `renderQRCode` such as `renderQRCode(123)`, the util fails with a cryptic message. I suggest either make a strict error + types for when input is not a string or trying to stringify input using `JSON.stringify`

----

ref: https://github.com/unjs/listhen/pull/97

<img width="708" alt="image" src="https://github.com/unjs/uqr/assets/5158436/74751dd3-4d5a-4273-b79d-86822ac79961">

**Comment by antfu** [comment]
<img width="877" alt="Screenshot 2023-08-12 at 17 39 55" src="https://github.com/unjs/uqr/assets/11247099/905e96b2-c741-4b82-8bdc-b4534026743d">

It does not allow numbers as the argument. And I think the type is already strict:

https://github.com/unjs/uqr/blob/01ba7fd43de88633ebce052f63599f7bbf8baa70/src/types.ts#L1-L6

**Comment by pi0** [comment]
Fair enough i think the issue with listhen upsteam is that cli implicitly does that and i didn't notice the problem but maybe making uqr more runtime safe? (i could quickly get the issue but users might have hard time to find)
