### ISSUE TITLE
Incorrect JSDoc description for `renderSVG`

### ISSUE THREAD

**Issue by TheCommieAxolotl** [unjs/uqr#3]
The [JSDoc typings for `renderSVG`](https://github.com/unjs/uqr/blob/main/src/svg.ts#L5) incorrectly label it as `renderANSI`.

```diff
/**
- * Render QR Code with ANSI color for terminal
+ * Render QR Code as SVG string
 */
```

**Comment by antfu** [comment]
Nice catch, interested in sending a quick PR? Thanks

**Comment by AakashRawat04** [comment]
I have made a PR for this.. This is my first time contributing in open source.. do let me know if i have to change anything. :rocket: @antfu
