### ISSUE TITLE
support logo image

### ISSUE THREAD

**Issue by sondh0127** [unjs/uqr#5]
### Describe the feature

![image](https://github.com/unjs/uqr/assets/62163604/db17acd6-32bf-43f5-b59f-56ac4739943e)
option to add image logo

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by antfu** [comment]
Thanks for bringing this up, but I believe it's out-of-scope of this project.

**Comment by krisantuswanandi** [comment]
@antfu what about render as jpg / png? is it also out of scope?

**Comment by krisantuswanandi** [comment]
not specific to jpg / png, just anything to put on an image tag and is downloadable

**Comment by krisantuswanandi** [comment]
and that's why it's preferable to render it as something "user-friendly" like jpg / png. but i understand if it's out of scope of this project, thanks so much for the reply @stokito !
